### ISSUE TITLE
PrincipalTest no encontrado.

### ISSUE THREAD

**Issue by rlp0019** [rlp0019/Activiti-Api#13]
Al realizar los test automáticamente mediante Ant, jacoco no encuentra la class PrincipalTest.

**Comment by clopezno** [comment]
Entiendo que es un problema de nombres. 
![imagen](https://user-images.githubusercontent.com/1453744/53866831-c7e7bf00-3ff2-11e9-823f-2a46814901c6.png)

En Java el nombre cualificado de la clase es el nombre de los paquetes que la contienen separados por puntos y añadiendo al final el nombre de la clase. En tu caso concreto es `test.PrincipalTest.class`

Cuando se compila en Java se crea una estructura de carpetas que concuerda con la estructura de paquetes. En tu proyecto has creado manualmente una carpeta` test` donde has incluido los fuentes. 

![imagen](https://user-images.githubusercontent.com/1453744/53867324-e601ef00-3ff3-11e9-9f84-6e9fa9bd985f.png)

En este caso se está buscando la clase en `build/test/`, la ejecucción de la tarea de Ant nos indica que no la encuentra porque está en` build/test/test`.

He hecho la prueba de eliminar la sentencia de empaquetar la clase de test `package test;`  y tu tarea ANT llamada `compilar-test`  termina con éxito y genera el informe de cobertura.

![imagen](https://user-images.githubusercontent.com/1453744/53868286-016df980-3ff6-11e9-8fd4-f6bd717514f1.png)

**Comment by rlp0019** [comment]
Buenos días,


No encuentro la sentencia de empaquetar la clase de test package test; que me has comentado, ¿en qué línea se encuentra?


Un saludo y gracias,

Roberto.


________________________________
De: Carlos López <notifications@github.com>
Enviado: miércoles, 6 de marzo de 2019 10:00
Para: rlp0019/Activiti-Api
Cc: Roberto Luquero Peñacoba; Assign
Asunto: Re: [rlp0019/Activiti-Api] PrincipalTest no encontrado. (#13)


Entiendo que es un problema de nombres.
[imagen]<https://user-images.githubusercontent.com/1453744/53866831-c7e7bf00-3ff2-11e9-823f-2a46814901c6.png>

[https://user-images.githubusercontent.com/1453744/53866831-c7e7bf00-3ff2-11e9-823f-2a46814901c6.png]

En Java el nombre cualificado de la clase es el nombre de los paquetes que la contienen separados por puntos y añadiendo al final el nombre de la clase. En tu caso concreto es test.PrincipalTest.class

Cuando se compila en Java se crea una estructura de carpetas que concuerda con la estructura de paquetes. En tu proyecto has creado manualmente una carpeta test donde has incluido los fuentes.

[imagen]<https://user-images.githubusercontent.com/1453744/53867324-e601ef00-3ff3-11e9-9f84-6e9fa9bd985f.png>

En este caso se está buscando la clase en build/test/, la ejecucción de la tarea de Ant nos indica que no la encuentra porque está en build/test/test.

He hecho la prueba de eliminar la sentencia de empaquetar la clase de test package test; y tu tarea ANT llamada compilar-test termina con éxito y genera el informe de cobertura.

[imagen]<https://user-images.githubusercontent.com/1453744/53868286-016df980-3ff6-11e9-8fd4-f6bd717514f1.png>

**Comment by clopezno** [comment]
Es la primera sentencia de la clase `PrincipalTest`,  `package test;`
Cuando  elimines  la sentencia el compilador te obligará a realizar una refactorización MoveClass, es decir, tendrás que mover  el fichero  `PrincipalTest.java` a la carpeta `test` y no a la carpeta `test/test`.

Si mueves la clase desde la vista de explorador de paquetes de Eclipse se aplica la refactorización directamente.

**Comment by rlp0019** [comment]
Pensé que estaba dentro de la ejecución de Jacoco.
De acuerdo, ahora lo cambio, gracias.
