### ISSUE TITLE
Cálculo de valores umbrales

### ISSUE THREAD

**Issue by clopezno** [rlp0019/Activiti-Api#25]
Roberto escribío:
_"No me queda completamente claro como realizar los percentiles. Es cierto que en la práctica de Desarrollo avanzado de aplicaciones software hicimos algo similar, pero a la hora de calcularlos, los multiplicamos por el número de líneas de código del proyecto y dividimos entre el total. ¿Por qué he de multiplicar y dividir en este caso?"_

**Contestación de Carlos**
Al tratarse de medidas de proceso no vamos ponderar por el tamaño del producto. En este caso el cálculo se simplifica ya que habrá que calcular los percentiles de cada medida de cada repositorio. En el siguiente [enlace](https://clopezno.github.io/agile_practices_experiment/) tienes un conjunto de datos que te pueden servir de prueba. Por ejemplo con ese conjunto de datos Q1_I3=87 y Q3_I3=100 .

**Comment by rlp0019** [comment]
De acuerdo entonces, ¿es este [ejemplo de Wikipedia](https://es.wikipedia.org/wiki/Percentil) correcto o existe otra fórmula a utilizar?

**Comment by clopezno** [comment]
La definición de las fórmulas son correctas.
Si quieres implementar el cálculo de percentiles/quartiles en Java te aconsejo que utilices la biblioteca apache commons maths http://commons.apache.org/proper/commons-math/userguide/stat.html.

Usa la clase DescriptiveStatistics.
