### ISSUE TITLE
Probar aplicación con Linux.

### ISSUE THREAD

**Issue by rlp0019** [rlp0019/Activiti-Api#36]
## Planteamiento
Probar la compatibilidad de la aplicación con Linux.

**Comment by clopezno** [comment]
Carga la aplicación correctamente en Linux pero falta probar cuando se solucione la issue de guardado en Base de datos definida en #37

**Comment by clopezno** [comment]
Probado en linux con éxito la versión Activiti-api 20/05/2019. Evaluación de un proyecto en Github comparando sobre resultados BD. Se añade el proyecto a BD.
