### ISSUE TITLE
Probar guardado en la base de datos.

### ISSUE THREAD

**Issue by rlp0019** [rlp0019/Activiti-Api#37]
## Planteamiento
Probar la funcionalidad del guardado en la base de datos.

**Comment by clopezno** [comment]
No encuentra el fichero de datos .csv porque está en jar
![ErrorGuardadoBaseDatos](https://user-images.githubusercontent.com/1453744/56953242-56cd0f80-6b3c-11e9-878e-ffa3c8da1300.png)

Posible solución: 

- Distribuir la aplicación con . jar y una carpeta .\data donde este el fichero inicial
- Esta opción implica utilizar una aplicación para instalar la aplicación que copie el fichero en una ubicación que indique el usuario.
- Esta opción permitiría sacar las bibliotecas fuera del jar y copiarlas en un directotio .\lib en la distribución.

**Comment by rlp0019** [comment]
He arreglado el cargado/guardado en la base de datos .csv. Lo único que faltaría para que funcionase correctamente es la aplicación para instalar el .jar y la carpeta data con el .csv. ¿Qué aplicación podría utilizar para ello?

**Comment by clopezno** [comment]
Damos por buena la solución de distribuir en un zip el binario y los recursos de datos necesarios. Aunque una posible mejora será utilizar un instalador.
